spring:
  application:
    name: config-verver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xiangwang001i/ConfigServer.git
          search-paths: config-repos
          username: 1015253657@qq.com
          password: XiangWang945.
      label: main
server:
  port: 8093